build.gradle
src/main/java/com/example/linkcargo/domain/cargo/Cargo.java
src/main/java/com/example/linkcargo/domain/chat/Attachment.java
src/main/java/com/example/linkcargo/domain/chat/ChatRoom.java
src/main/java/com/example/linkcargo/domain/chat/Membership.java
src/main/java/com/example/linkcargo/domain/chat/Message.java
src/main/java/com/example/linkcargo/domain/chat/RoomStatus.java
src/main/java/com/example/linkcargo/domain/forwarding/Forwarding.java
src/main/java/com/example/linkcargo/domain/history/History.java
src/main/java/com/example/linkcargo/domain/news/News.java
src/main/java/com/example/linkcargo/domain/notification/Notification.java
src/main/java/com/example/linkcargo/domain/port/Port.java
src/main/java/com/example/linkcargo/domain/prediction/PeriodType.java
src/main/java/com/example/linkcargo/domain/prediction/Prediction.java
src/main/java/com/example/linkcargo/domain/quotation/Quotation.java
src/main/java/com/example/linkcargo/domain/schedule/PortType.java
src/main/java/com/example/linkcargo/domain/schedule/Schedule.java
src/main/java/com/example/linkcargo/domain/schedule/TransportType.java
src/main/java/com/example/linkcargo/domain/user/Role.java
src/main/java/com/example/linkcargo/domain/user/Status.java
src/main/java/com/example/linkcargo/domain/user/User.java
src/main/java/com/example/linkcargo/global/entity/BaseEntity.java

feat: 도메인 별 엔티티 추가

---

src/main/java/com/example/linkcargo/global/response/ApiResponse.java
src/main/java/com/example/linkcargo/global/response/code/BaseCode.java
src/main/java/com/example/linkcargo/global/response/code/BaseErrorCode.java
src/main/java/com/example/linkcargo/global/response/code/ErrorReasonDto.java
src/main/java/com/example/linkcargo/global/response/code/ReasonDto.java
src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java
src/main/java/com/example/linkcargo/global/response/code/resultCode/SuccessStatus.java
src/main/java/com/example/linkcargo/global/response/exception/ExceptionAdvice.java
src/main/java/com/example/linkcargo/global/response/exception/GeneralException.java
src/main/java/com/example/linkcargo/global/response/exception/handler/GeneralHandler.java

feat: API 응답 통일 기능

---

src/main/java/com/example/linkcargo/LinkcargoApplication.java
src/main/java/com/example/linkcargo/domain/port/PortRepository.java
src/main/java/com/example/linkcargo/domain/schedule/ScheduleController.java
src/main/java/com/example/linkcargo/domain/schedule/ScheduleRepository.java
src/main/java/com/example/linkcargo/domain/schedule/ScheduleService.java
src/main/java/com/example/linkcargo/domain/schedule/dto/request/ScheduleCreateRequest.java
src/main/java/com/example/linkcargo/domain/schedule/dto/request/ScheduleCreateUpdateRequest.java
src/main/java/com/example/linkcargo/domain/schedule/dto/response/ScheduleInfoResponse.java
src/main/java/com/example/linkcargo/domain/schedule/dto/response/ScheduleListResponse.java
src/main/java/com/example/linkcargo/global/config/SwaggerConfig.java
src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java
src/main/java/com/example/linkcargo/global/response/exception/handler/PortHandler.java
src/main/java/com/example/linkcargo/global/response/exception/handler/ScheduleHandler.java

feat: 선박 스케줄 CRUD

---

src/main/java/com/example/linkcargo/domain/cargo/CargoController.java
src/main/java/com/example/linkcargo/domain/cargo/CargoService.java

- Resolves #8 
- 화물 여러 개 추가 기능

feat: 화물 여러 개 추가 기능 

---

src/main/java/com/example/linkcargo/domain/schedule/ScheduleController.java

- Resolves #22 
- schedule의 모든 API의 인증 방법을 @AuthenticationPrincipal을 이용한 방법으로 수정

refactor: schedule 인증 방법 수정

---

src/main/java/com/example/linkcargo/domain/port/PortController.java
src/main/java/com/example/linkcargo/domain/port/PortRepository.java
src/main/java/com/example/linkcargo/domain/port/PortService.java
src/main/java/com/example/linkcargo/domain/port/dto/request/PortCreateUpdateRequest.java
src/main/java/com/example/linkcargo/domain/port/dto/response/PortReadResponse.java
src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java

feat: 항구 CRUD

---

src/main/java/com/example/linkcargo/domain/quotation/Quotation.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationController.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationRepository.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationService.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationStatus.java
src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationConsignorRequest.java
src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java
src/main/java/com/example/linkcargo/global/response/exception/handler/QuotationHandler.java

feat: quotation 생성

---

src/main/java/com/example/linkcargo/domain/port/PortController.java
src/main/java/com/example/linkcargo/domain/port/PortRepository.java
src/main/java/com/example/linkcargo/domain/port/PortService.java

feat: PortType에 따른 Port 조회

---

src/main/java/com/example/linkcargo/domain/cargo/Cargo.java
src/main/java/com/example/linkcargo/domain/cargo/CargoController.java
src/main/java/com/example/linkcargo/domain/cargo/CargoService.java
src/main/java/com/example/linkcargo/domain/cargo/dto/CargoDTO.java
src/main/java/com/example/linkcargo/domain/cargo/dto/request/CargoRequest.java
src/main/java/com/example/linkcargo/domain/cargo/dto/request/CargosRequest.java

- Resolves #45 
- 화물 정보 입력 - 피그마에 맞게 수정

Feat: 화물 정보 입력 - 피그마에 맞게 수정

---

src/main/java/com/example/linkcargo/domain/quotation/Quotation.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationCalculationService.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationController.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationRepository.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationService.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationStatus.java
src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationConsignorRequest.java
src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationForwarderRequest.java
src/main/java/com/example/linkcargo/global/config/GlobalConfig.java
src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java

- Resolves #40 
- 화주가 작성한 견적서 업데이트
- 화주가 견적서 작성 시 알고리즘에 의한 견적서 생성

feat: 포워더/알고리즘에 의한 견적서 업데이트

---

src/main/java/com/example/linkcargo/domain/schedule/Schedule.java
src/main/java/com/example/linkcargo/domain/schedule/ScheduleController.java
src/main/java/com/example/linkcargo/domain/schedule/ScheduleRepository.java
src/main/java/com/example/linkcargo/domain/schedule/ScheduleService.java
src/main/java/com/example/linkcargo/domain/schedule/dto/request/ScheduleCreateUpdateRequest.java

- Resolves #39 
- schedule 엔티티 속성 추가
- schedule 검색 조건 변경

refactor: schedule api 변경 사항 업데이트

---

src/main/java/com/example/linkcargo/domain/forwarding/Forwarding.java
src/main/java/com/example/linkcargo/domain/forwarding/ForwardingController.java
src/main/java/com/example/linkcargo/domain/forwarding/ForwardingRepository.java
src/main/java/com/example/linkcargo/domain/forwarding/ForwardingService.java
src/main/java/com/example/linkcargo/domain/forwarding/dto/request/ForwardingCreateUpdateRequest.java
src/main/java/com/example/linkcargo/domain/forwarding/dto/response/ForwardingInfoResponse.java
src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java
src/main/java/com/example/linkcargo/global/response/exception/handler/ForwardingHandler.java

- Resolves #41 
- Forwarding 엔티티 정의
- Forwarding CRUD 기능
- 유저 포워딩 업체 선정 기능

feat: 포워딩 CRUD

---

src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationConsignorRequest.java
src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationForwarderRequest.java

- Resolves #52 
- 포워더 견적서 특이사항 작성

refactor: 포워더 견적서 업데이트 시 특이사항 작성 추가

---

build.gradle
src/main/java/com/example/linkcargo/domain/dashboard/DashboardController.java
src/main/java/com/example/linkcargo/domain/dashboard/DashboardService.java
src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardPredictionReasonResponse.java
src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardPredictionResponse.java
src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardQuotationCompareResponse.java
src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardQuotationResponse.java
src/main/java/com/example/linkcargo/domain/prediction/Prediction.java
src/main/java/com/example/linkcargo/domain/prediction/PredictionRepository.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationCalculationService.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationController.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationRepository.java
src/main/java/com/example/linkcargo/domain/quotation/dto/response/QuotationInfoResponse.java
src/main/java/com/example/linkcargo/global/config/GlobalConfig.java

- Resolves #42 
- 가장 싼 견적서 조회 기능
- 견적서 비교 조회 기능
- 운임 비용 그래프 정보 조회 기능
- 운임 비용 이유 정보 조회 기능

feat: 대시보드 화면 (1)

---

src/main/java/com/example/linkcargo/domain/chat/ChatRestController.java
src/main/java/com/example/linkcargo/domain/test/testController.java
src/main/java/com/example/linkcargo/domain/token/dto/request/UserRegisterRequest.java
src/main/java/com/example/linkcargo/domain/user/User.java
src/main/java/com/example/linkcargo/domain/user/UserController.java
src/main/java/com/example/linkcargo/domain/user/UserS3Service.java
src/main/java/com/example/linkcargo/domain/user/UserService.java
src/main/java/com/example/linkcargo/domain/user/dto/UserDTO.java
src/main/java/com/example/linkcargo/domain/user/dto/request/UserPasswordUpdateRequest.java
src/main/java/com/example/linkcargo/domain/user/dto/response/FileResponse.java
src/main/java/com/example/linkcargo/domain/user/dto/response/UserResponse.java
src/main/java/com/example/linkcargo/global/response/code/resultCode/ErrorStatus.java

- Resolves #48 
- 사용자 정보(프로필 이미지 포함) 조회, 수정

feat: 사용자 정보(프로필 이미지 포함) 조회, 수정 

---

src/main/java/com/example/linkcargo/domain/dashboard/DashboardController.java
src/main/java/com/example/linkcargo/domain/dashboard/DashboardService.java
src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardNewsResponse.java
src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardPortCongestionResponse.java
src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardRecommendationResponse.java
src/main/java/com/example/linkcargo/domain/news/NewsRepository.java
src/main/java/com/example/linkcargo/domain/prediction/PredictionRepository.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationCalculationService.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationRepository.java
src/main/java/com/example/linkcargo/domain/schedule/ScheduleRepository.java

- Resolves #42 
- 항구 혼잡도 관련 정보 조회 기능
- 사용자 관심사에 따른 뉴스 요약 기능
- 운임비용이 가장 저렴할때의 예상 비용과 선박 스케줄 정보 조회 기능

feat: 대시보드 API (2)

---

src/main/java/com/example/linkcargo/domain/dashboard/DashboardController.java
src/main/java/com/example/linkcargo/domain/dashboard/DashboardService.java
src/main/java/com/example/linkcargo/domain/quotation/Quotation.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationCalculationService.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationController.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationRepository.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationService.java
src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationConsignorRequest.java
src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationForwarderRequest.java
src/main/java/com/example/linkcargo/domain/quotation/dto/response/QuotationInfoResponse.java

- Resolves #62 
- originalQuotationId 속성 추가
- 대시보드에서 Quotation 관련 조회 시 quotationId 사용
- 포워더가 견적서 업데이트 시 새로운 Quotation 엔티티 생성

refactor: Quotation 관련 변경

---

src/main/java/com/example/linkcargo/domain/cargo/Cargo.java
src/main/java/com/example/linkcargo/domain/cargo/CargoController.java
src/main/java/com/example/linkcargo/domain/cargo/CargoService.java
src/main/java/com/example/linkcargo/domain/cargo/dto/CargoDTO.java
src/main/java/com/example/linkcargo/domain/cargo/dto/request/CargoRequest.java
src/main/java/com/example/linkcargo/domain/cargo/dto/response/CargoIdsResponse.java

- Resolves #64 
- 화물 입력 데이터 및 저장 후 반환 데이터 수정

Feat: 화물 입력 데이터 및 저장 후 반환 데이터 수정

---

src/main/java/com/example/linkcargo/domain/news/NewsController.java
src/main/java/com/example/linkcargo/domain/news/NewsService.java

- Resolves #55 
- 뉴스 엔티티를 생성하는 API

feat: News 생성 API

---

build.gradle
src/main/java/com/example/linkcargo/domain/dashboard/DashboardController.java
src/main/java/com/example/linkcargo/domain/dashboard/DashboardService.java
src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardRawQuotationResponse.java
src/main/java/com/example/linkcargo/domain/quotation/Quotation.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationCalculationService.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationController.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationRepository.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationService.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationStatus.java
src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationConsignorRequest.java
src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationForwarderRequest.java
src/main/java/com/example/linkcargo/domain/quotation/dto/request/QuotationRawRequest.java
src/main/java/com/example/linkcargo/global/config/OpenAIConfig.java

- Resolves #70 
- 대시보드 API 파라미터 수정
- Quotation에 RAW_SHEET status 추가 및 rawQuotationId 속성 추가
- Quotation 속성 추가로 인한 로직 변경
- 운임지수, 뉴스 관련 OpenAI API 사용

refactor: 대시보드 전체 수정

---

src/main/java/com/example/linkcargo/domain/quotation/QuotationCalculationService.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationController.java
src/main/java/com/example/linkcargo/domain/quotation/QuotationService.java
src/main/java/com/example/linkcargo/domain/quotation/dto/response/EstimatedQuotationResponse.java
src/main/java/com/example/linkcargo/domain/user/UserRepository.java

- Resolves #73 
- 화주 화물 입력 시 예상 비용 조회
- 화주 견적서 입력 시 예상 도착 견적서 조회

feat: 기타 견적서 API

---

src/main/java/com/example/linkcargo/domain/token/RefreshTokenService.java

- Resolves #79 
- 로그인 시 기존 리프레시 토큰 제거

로그인 시 기존 리프레시 토큰 제거

---

src/main/java/com/example/linkcargo/domain/token/RefreshToken.java
src/main/java/com/example/linkcargo/domain/token/RefreshTokenService.java

- Resolves #79 
- 리프레시 토큰 유니크, 재발급 시 기존 토큰 삭제 설정

리프레시 토큰 유니크, 재발급 시 기존 토큰 삭제 설정

---

src/main/java/com/example/linkcargo/domain/chat/ChatRestController.java

중복 어노테이션 제거

---

src/main/java/com/example/linkcargo/domain/user/UserS3Service.java
src/main/java/com/example/linkcargo/domain/user/dto/response/FilesResponse.java

파일 목록 조회 시 개수도 포함

---

src/main/java/com/example/linkcargo/domain/chat/ChatRestController.java
src/main/java/com/example/linkcargo/domain/user/UserS3Service.java
src/main/java/com/example/linkcargo/domain/user/dto/response/FilesResponse.java

(to main) 파일 목록 조회 시 개수도 포함

---

.gitignore

- 엑세스 토큰 만료시간 원상복귀
- 엑세스 토큰 만료시간 원상복귀

엑세스 토큰 만료시간 원상복귀

---

src/main/java/com/example/linkcargo/domain/chat/ChatRestController.java
src/main/java/com/example/linkcargo/domain/chat/ChatService.java
src/main/java/com/example/linkcargo/domain/chat/ChatStompController.java
src/main/java/com/example/linkcargo/domain/chat/Entity/ChatRoom.java
src/main/java/com/example/linkcargo/domain/chat/dto/request/ChatRoomIdRequest.java

채팅방 목록 조회 시 채팅방 상세 정보 추가

---

src/main/java/com/example/linkcargo/domain/chat/ChatService.java

-문의하기 버튼 누를때마다 현재 확인하고 있는 스케줄로 채팅방 스케줄 정보 수정

문의하기 버튼 누를때마다 현재 확인하고 있는 스케줄로 채팅방 스케줄 정보 수정

---

src/main/java/com/example/linkcargo/global/jwt/JwtAuthorizationFilter.java

항구 조회, 운임료 계산 API 인증 해제
- 항구 조회, 운임료 계산 API 인증 해제

항구 조회, 운임료 계산 API 인증 해제

---

src/main/java/com/example/linkcargo/domain/dashboard/DashboardController.java
src/main/java/com/example/linkcargo/domain/dashboard/DashboardService.java
src/main/java/com/example/linkcargo/domain/dashboard/dto/response/DashboardQuotationCompareResponse.java

- Resolves #98 
- 견적서를 AI를 통해 요약하여 보고서 형식으로 반환하는 기능

feat: quotation ai 요약 보고서

---

src/main/java/com/example/linkcargo/domain/notification/Notification.java
src/test/java/com/example/linkcargo/EmailTest.java

테스트 코드 주석처리

---

src/main/java/com/example/linkcargo/domain/notification/Notification.java
src/main/java/com/example/linkcargo/domain/notification/dto/NotificationDTO.java

- Resolves #67 
-알림 DTO 에 생성 시간 추가

알림 DTO 에 생성 시간 추가

---

src/main/java/com/example/linkcargo/domain/chat/Entity/Chat.java

채팅 내용 길이 제한 늘림

---

src/main/java/com/example/linkcargo/domain/chat/ChatService.java

- Resolves #25
-채팅 읽음 null 일때(예전 데이터) 핸들링

채팅 읽음 null 일때(초기 데이터) 핸들링

---

src/main/java/com/example/linkcargo/domain/notification/EmailService.java
src/main/resources/templates/email.html
src/test/java/com/example/linkcargo/EmailTest.java

- Resolves #67 
- 이메일 알림 html 수정

이메일 알림 HTML 수정

---

build.gradle
src/main/java/com/example/linkcargo/domain/chat/ChatService.java
src/main/java/com/example/linkcargo/domain/chat/ChatStompController.java
src/main/java/com/example/linkcargo/domain/chat/Entity/ChatRoom.java
src/main/java/com/example/linkcargo/domain/chat/repository/ChatRoomRepository.java
src/test/java/com/example/linkcargo/EmailTest.java

- Resolves #113 
-채팅방 목록 조회 시 최근 대화 순으로

채팅방 목록 조회 시 최근 대화 순으로
